import {scene,layer,uid} from './state.js';
// Provider boundary: front-end produces deterministic editable drafts only. Network providers belong behind a server endpoint.
export const providers={image:{name:'Image provider',requiresServer:true},video:{name:'Video provider',requiresServer:true},copy:{name:'Local creative assistant',requiresServer:false}};
const words=s=>s.replace(/[^\w\s]/g,'').split(/\s+/).filter(Boolean);
export function brief(prompt){let w=words(prompt), platform=/linkedin/i.test(prompt)?'LinkedIn':/youtube/i.test(prompt)?'YouTube':'Instagram';return {goal:prompt||'Create a high-impact social creative',audience:/professional/i.test(prompt)?'Young professionals':'Social-first audiences',platform,tone:/luxury|premium/i.test(prompt)?'Premium and cinematic':'Direct and energetic',hook:`${w.slice(0,5).join(' ')||'A better way to create'}.`,cta:'Create yours today'} }
export function concepts(b){return ['Bold contrast','Benefit-first','Social proof'].map((title,i)=>({id:i,title,hook:[b.hook,'What if it was this simple?','The result speaks first.'][i],angle:['Pattern interrupt then product reveal','Problem to payoff narrative','Proof-led conversion story'][i]}))}
export function director(prompt,choice=0){let b=brief(prompt), c=concepts(b)[choice];return {brief:b,concept:c,scenes:[scene({name:'Hook',duration:3,layers:[layer('text',{text:c.hook,fontSize:10,x:8,y:28,w:84,h:25,animation:'kinetic',end:3})]}),scene({name:'Problem',duration:3,layers:[layer('text',{text:'The old way costs attention.',fontSize:8,x:10,y:35,w:80,h:18,animation:'flip',end:3})]}),scene({name:'Reveal',duration:4,layers:[layer('text',{text:'Meet the better way.',fontSize:9,x:10,y:33,w:80,h:20,animation:'spotlight',end:4})]}),scene({name:'CTA',duration:3,layers:[layer('text',{text:b.cta,fontSize:9,x:15,y:38,w:70,h:16,animation:'pulse',end:3,color:'#ffc857'})]})]}}
export function copilot(project,instruction){let s=instruction.toLowerCase();if(/premium|luxury/.test(s))return {label:'Premium styling',apply:p=>p.scenes.forEach(x=>{x.background='#17120d';x.layers.forEach(l=>{if(l.type==='text')l.color=l.color==='#ffc857'?l.color:'#fff7df'})})};if(/strong|hook/.test(s))return {label:'Strengthen hook',apply:p=>{let l=p.scenes[0].layers.find(x=>x.type==='text');if(l)l.text='WAIT — THIS CHANGES EVERYTHING.'}};if(/shorten/.test(s))return {label:'Shorten narrative',apply:p=>p.scenes.splice(Math.max(2,p.scenes.length-1))};if(/extend/.test(s))return {label:'Extend timing',apply:p=>p.scenes.forEach(x=>x.duration+=1)};return {label:'Refresh copy',apply:p=>p.scenes.forEach((x,i)=>x.layers.filter(l=>l.type==='text').forEach(l=>l.text=i===0?'Designed to stop the scroll.':l.text))}}
export function replace(layer,prompt){return {...layer,id:uid('layer'),name:'AI '+layer.name,text:layer.type==='text'?(prompt||'A newly generated idea'):layer.text,assetPrompt:prompt,generated:true}}
