const KEY='thumbstop-studio-v2';
const uid=(p='id')=>`${p}_${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;
export const aspect={reel:[1080,1920],square:[1080,1080],landscape:[1920,1080],feed:[1080,1350]};
export function layer(type, props={}) { return {id:uid('layer'),type,name:props.name||type[0].toUpperCase()+type.slice(1),x:props.x??12,y:props.y??18,w:props.w??76,h:props.h??18,rotation:0,opacity:1,visible:true,locked:false,start:0,end:props.end??5,z:props.z??1,text:props.text||'',color:props.color||'#ffffff',fontSize:props.fontSize||8,assetId:props.assetId||null,animation:props.animation||'pulse',effects:[],keyframes:[],...props}; }
export function scene(props={}) { return {id:uid('scene'),name:props.name||'Scene',duration:props.duration||5,background:props.background||'#151120',layers:props.layers||[],transition:'fade',...props}; }
export function project(props={}) { const s=scene({name:'Hook',duration:3,layers:[layer('text',{name:'Headline',text:'Make them stop scrolling.',x:10,y:30,w:80,h:20,fontSize:10,animation:'kinetic'}),layer('text',{name:'CTA',text:'Try Thumbstop',x:22,y:66,w:56,h:10,fontSize:5,color:'#ffc857',animation:'pulse'})]}); return {id:uid('project'),name:'Untitled creative',createdAt:Date.now(),updatedAt:Date.now(),format:'reel',scenes:[s],audioTracks:[],captions:[],brandKitId:null,metadata:{objective:'Brand awareness',platform:'Instagram'},export:{fps:30,quality:'1080p'},...props}; }
const seed={projects:[],assets:[],brandKits:[{id:'brand_default',name:'Thumbstop',colors:['#ff4d6d','#ffc857','#151120'],font:'Manrope'}],mode:'simple',history:[],future:[]};
let data=load(); let listeners=[]; let timer;
function load(){try{return {...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...seed}}}
function persist(){clearTimeout(timer);document.querySelector('#saveState')?.replaceChildren('Saving…');timer=setTimeout(()=>{localStorage.setItem(KEY,JSON.stringify(data));document.querySelector('#saveState')?.replaceChildren('All changes saved')},250)}
export const store={get:()=>data,subscribe(fn){listeners.push(fn);return()=>listeners=listeners.filter(x=>x!==fn)},commit(label,fn){data.history.push({label,snapshot:structuredClone(data.projects)});if(data.history.length>60)data.history.shift();data.future=[];fn(data);persist();listeners.forEach(x=>x(data));},set(key,value){data[key]=value;persist();listeners.forEach(x=>x(data));},undo(){let h=data.history.pop();if(!h)return false;data.future.push(structuredClone(data.projects));data.projects=h.snapshot;persist();listeners.forEach(x=>x(data));return h.label},redo(){let n=data.future.pop();if(!n)return false;data.history.push({label:'Redo',snapshot:structuredClone(data.projects)});data.projects=n;persist();listeners.forEach(x=>x(data));return true}};
export function getProject(id){return store.get().projects.find(p=>p.id===id)}
export function makeProject(props){let p=project(props);store.commit('Create project',d=>d.projects.unshift(p));return p}
export {uid};
